          <p>
            Die folgende Liste enth&auml;lt die wichtigsten f&uuml;r
            den Benutzer sichtbaren &Auml;nderungen an LIVE seit der
            letzten stabilen Version.
          </p>
          <p>

	    Die größeren neuen Features wurden dieses mal von
	    LIVE-Anwendern bereit gestellt. Wir freuen uns über die
	    Beteiligung und <strong>danken allen</strong> die dazu
	    beigetragen haben, dass LIVE besser wird von ganzem
	    Herzen.

          </p>
          <p>
	    Die Namen der Entwickler, können in der Versions-Historie
	    im LIVE-Git nachgelesen werden.
          </p>
          <ul>
            <li>
	      Es gibt eine neue <strong>Programübersicht mehrerer
	      Kanäle</strong> gleichzeitig. Die Programme können nach
	      eigenen Vorlieben gruppiert werden und es können
	      Zeitpunkt wie Primetime, Nachmittagsprogramm,
	      Nachtprogram etc. definiert werden.
            </li>
            <li>
	      Die <strong>Aufnahmen-Seite wurde etwas
	      aufgefrischt</strong> und hat ein paar neue Features
	      erhalten:
	      <ul>
	        <li>
		  <strong>HTTP streaming von Aufnahmen</strong> wenn
		  tntnet > 1.7.0 verfügbar ist.  In dem Browser muss
		  allerding das mozilla-vlc Plugin laufen.
		</li>
	        <li>

		  Es können nun mehrere <strong>Aufnahmen gleichzeitig
		  gelöscht</strong> werden.

		</li>
	        <li>

                  Mehrere Aufnahmen können an einen <strong>anderen
                  Ort verschoben oder kopiert</strong> werden.

		</li>
	        <li>

                  Die Liste der Aufnahmen kann mit normalen Strings
                  oder mit Regulären Ausdrücken
                  <strong>gefiltert</strong> werden.


		</li>
	        <li>

                  Es können alle <strong>Aufnahmen-Ordner</strong> auf
                  einmal <strong>aufgeklappt und zugeklappt</strong>
                  werden. Das ist besonders hilfreich, wenn gefiltert
                  wurde.

		</li>
	      </ul>
	    </li>
            <li>

	      Funktioniert auch mit VDR Entwicklerversionen
	      (1.7.x). Unterstützt das neue
	      <strong>TS-Aufnahmeformat</strong>.

	    </li>
            <li>

	      Die Kanäle haben jetzt auch <strong>Nummeren</strong>.

	    </li>
            <li>

	      Support für <strong>IPv6</strong>.

	    </li>
            <li>

	      LIVE kann jetzt auch via <strong>SSL
	      angesprochen</strong> werden.

	    </li>
            <li>

	      Verbesserter Support für <strong>EPG-Bilder</strong> die
	      von externen Tools (tvm2vdr.pl) bereit gestellt werden
	      können.

	    </li>
            <li>
	      Übersetzungen für Italienisch, Finnisch, Polnisch,
	      Spanisch und Slowakisch
	    </li>
            <li>
	      Zahlreiche kleine Bug-Fixes.
	    </li>
          </ul>
