          <p>
            Die folgende Liste enth&auml;lt die wichtigsten f&uuml;r
            den Benutzer sichtbaren &Auml;nderungen an LIVE seit der
            letzten stabilen Version.
          </p>
          <p>
	    Die gr&ouml;&szlig;eren neuen Features wurden dieses mal
	    von LIVE-Anwendern bereit gestellt. Wir freuen uns
	    &uuml;ber die Beteiligung und <strong>danken
	    allen</strong> die dazu beigetragen haben, dass LIVE
	    besser wird von ganzem Herzen.
          </p>
          <p>
	    Die Namen der Entwickler, k&ouml;nnen in der Versions-Historie
	    im LIVE-Git nachgelesen werden.
          </p>
          <ul>
            <li>
	      Es gibt eine neue <strong>Program&uuml;bersicht mehrerer
	      Kan&auml;le</strong> gleichzeitig. Die Programme k&ouml;nnen nach
	      eigenen Vorlieben gruppiert werden und es k&ouml;nnen
	      Zeitpunkt wie Primetime, Nachmittagsprogramm,
	      Nachtprogram etc. definiert werden.
            </li>
            <li>
	      Die <strong>Aufnahmen-Seite wurde etwas
	      aufgefrischt</strong> und hat ein paar neue Features
	      erhalten:
	      <ul>
	        <li>
		  <strong>HTTP streaming von Aufnahmen</strong> wenn
		  tntnet > 1.7.0 verf&uuml;gbar ist.  In dem Browser muss
		  allerding das mozilla-vlc Plugin laufen.
		</li>
	        <li>
		  Es k&ouml;nnen nun mehrere <strong>Aufnahmen gleichzeitig
		  gel&ouml;scht</strong> werden.
		</li>
	        <li>
                  Mehrere Aufnahmen k&ouml;nnen an einen <strong>anderen
                  Ort verschoben oder kopiert</strong> werden.
		</li>
	        <li>
                  Die Liste der Aufnahmen kann mit normalen Strings
                  oder mit Regul&auml;ren Ausdr&uuml;cken
                  <strong>gefiltert</strong> werden.
		</li>
	        <li>
                  Es k&ouml;nnen alle <strong>Aufnahmen-Ordner</strong> auf
                  einmal <strong>aufgeklappt und zugeklappt</strong>
                  werden. Das ist besonders hilfreich, wenn gefiltert
                  wurde.
		</li>
	      </ul>
	    </li>
            <li>
	      Funktioniert auch mit VDR Entwicklerversionen (1.7.x)
	      und ist f&uuml;r das angek&uuml;ndigte VDR 2.0 Release
	      vorbereitet.
	    </li>
            <li>
	      Unterst&uuml;tzt das neue
	      <strong>TS-Aufnahmeformat</strong>.
	    </li>
            <li>
	      Die Kan&auml;le haben jetzt auch
	      <strong>Nummern</strong>.
	    </li>
            <li>
	      Support f&uuml;r <strong>IPv6</strong>.
	    </li>
            <li>
	      LIVE kann jetzt auch via <strong>SSL
	      angesprochen</strong> werden.
	    </li>
            <li>
	      Verbesserter Support f&uuml;r
	      <strong>EPG-Bilder</strong> die von externen Tools
	      (tvm2vdr.pl) bereit gestellt werden k&ouml;nnen.
	    </li>
            <li>
	      &Uuml;bersetzungen f&uuml;r Italienisch, Finnisch,
	      Polnisch, Spanisch und Slowakisch
	    </li>
            <li>
	      Zahlreiche kleine Bug-Fixes (und vieleich auch neue
	      Bugs).
	    </li>
          </ul>
