	<div class="tab">
          <table class="listing" style="margin-bottom: 15px; width: 100%" cellspacing="0" cellpadding="0">
            <tr class="description">
	      <td><div class="withmargin">Software</div></td>
	      <td><div class="withmargin">Mindestversion</div></td>
	      <td><div class="withmargin">Empfohlenen</div></td>
	      <td><div class="withmargin">URL</div></td>
	    </tr>
            <tr>
	      <td><div class="withmargin">Tntnet</div></td>
	      <td><div class="withmargin">1.5.3</div></td>
	      <td><div class="withmargin">&gt;= 1.5.3</div></td>
	      <td><div class="withmargin"><a href="http://www.tntnet.org/download.html">http://www.tntnet.org/download.html</a></div></td>
	    </tr>
            <tr>
	      <td><div class="withmargin">Cxxtools</div></td>
	      <td><div class="withmargin">1.4.3</div></td>
	      <td><div class="withmargin">&gt;= 1.4.3</div></td>
	      <td><div class="withmargin"><a href="http://www.tntnet.org/download.html">http://www.tntnet.org/download.html</a></div></td>
	    </tr>
            <tr>
	      <td><div class="withmargin">VDR</td>
	      <td><div class="withmargin">1.4.3</td>
	      <td><div class="withmargin">&gt;= 1.4.7</td>
	      <td><div class="withmargin"><a href="http://www.cadsoft.de/vdr/download.htm">http://www.cadsoft.de/vdr/download.htm</a></div></td>
	    </tr>
            <tr>
	      <td><div class="withmargin">boost</div></td>
	      <td><div class="withmargin">1.32.0</div></td>
	      <td><div class="withmargin"></div></td>
	      <td><div class="withmargin"><a href="http://www.boost.org">http://www.boost.org</a></div></td>
	    </tr>
            <tr class="spacer">
	      <td colspan="4"></td>
	    </tr>
            <tr class="description">
	      <td colspan="4"><div class="withmargin">Verwendete VDR Plugins:</div></td>
	    </tr>
            <tr>
	      <td><div class="withmargin">epgsearch</div></td>
	      <td><div class="withmargin">0.9.22</div></td>
	      <td><div class="withmargin">&gt;= 0.9.22</div></td>
	      <td><div class="withmargin"><a href="http://winni.vdr-developer.org/epgsearch/index.html#download">http://winni.vdr-developer.org/epgsearch/index.html#download</a></div></td>
	    </tr>
          </table>
	</div>

          Tntnet stellt grundlegende Webserver-Funktionen für LIVE zur
          Verfügung.  Cxxtools wird von Tntnet benötigt.<br />
	  Boost stellt wichtige Datenstrukturen. Gegenwärtig benötigen
	  wir das Gesamtpaket, demnächst könnte es aber eine
	  abgespeckte Version, die nur das benötigte bereitstellt, von
	  uns geben.
