    <link rel="stylesheet" type="text/css" href="../styles.css" />
    <style type="text/css">
      <!--
	  /* ... Hier werden die Formate definiert ... */
div.screenshots {
  border: 1px solid black;
  padding: 5px;
}

div.screenshots img {
  padding: 7px;
  border: 1px solid #444444;
}

a {
  font-weight: bold;
}

div.tab {
  padding-left: 2.5em;
}

table.listing a {
  color: blue;
}

div.inhalt p {
  padding-left: 1em;
}
	-->
    </style>
